import operator
from typing import Annotated

from langgraph.graph import MessagesState
from typing_extensions import TypedDict


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    asset_type: Annotated[str, "Asset type under analysis such as stock or crypto"]
    instrument_context: Annotated[str, "Deterministic ticker identity resolved at run start"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    data_bundle: Annotated[dict, "Pre-fetched data bundle for the analysis run"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Sentiment Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]
    research_recommendation: Annotated[
        str, "Machine-readable 5-tier rating from the Research Manager (view-based scale)"
    ]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    trader_direction: Annotated[str, "Machine-readable Buy/Hold/Sell direction from the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    portfolio_rating: Annotated[
        str,
        "Machine-readable 5-tier rating from the Portfolio Manager, parsed out of "
        "the rendered **Rating** line. Same VIEW scale as portfolio_view (it "
        "briefly held the sizer's position-delta label, which broke comparability "
        "with the historical predictions.rating column).",
    ]
    portfolio_view: Annotated[
        str,
        "Machine-readable 5-tier VIEW rating from the Portfolio Manager — the "
        "like-for-like counterpart to research_recommendation and trader_direction",
    ]
    position_ceiling: Annotated[
        dict,
        "Ceiling.as_dict() from position_sizing: allowed weight, ATR%, stop "
        "distance, binding_constraint and method. A single-name fact (this "
        "stock's volatility), so it belongs in the graph. The *target* weight "
        "does not: it needs the other N-1 holdings and comes from "
        "tradingagents.portfolio.allocator after the batch completes.",
    ]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    user_portfolio_context: Annotated[
        str,
        "Human-readable holding summary for the REPORT layer only. Never inject "
        "this into a prompt: it carries the cost price, and reasoning from "
        "unrealised P&L is the bias documented in position_sizing. Decision "
        "agents read user_position instead.",
    ]
    user_position: Annotated[
        dict,
        "Structured holding facts: {'position_pct': float | None}. The weight is "
        "the only holding datum the decision agents may see — it is a sizing "
        "input, whereas cost price is not an input to anything.",
    ]

    # Run-integrity channel. Unlike every other field here, the Annotated
    # metadata is load-bearing: operator.add makes LangGraph *append* each
    # node's findings instead of overwriting, so a blank debate turn recorded
    # early in the run survives to the report. See
    # tradingagents.agents.utils.integrity for the finding shape.
    integrity_findings: Annotated[list[dict], operator.add]
