"""Render run-integrity findings into the HTML report.

The findings themselves are produced inside the graph (see
:mod:`tradingagents.agents.utils.integrity` and
:mod:`tradingagents.graph.reconciliation`) and travel on the final state's
``integrity_findings`` channel. This module only presents them.

Why the presentation lives here rather than in each renderer: the 2026-08-11
300760.SZ report was generated by the batch runner, but the same final state is
also rendered by the web server and the CLI. A banner implemented in one
renderer protects only that renderer.

Legacy final states saved before the ``integrity_findings`` channel existed have
no such key. For those this module recomputes what it can from the rendered
decision text, so old reports do not silently lose the rating/action check that
``run_batch_analysis.check_rating_action_warning`` used to perform.
"""

from __future__ import annotations

from collections.abc import Mapping

from tradingagents.agents.utils.integrity import (
    DATA_COMPLETENESS_SECTION_PREFIX,
    SEVERITY_BLOCK,
    classify_integrity_findings,
    stage_ratings,
)
from tradingagents.agents.utils.rating import (
    check_rating_action_consistency,
    parse_position_percents,
    parse_rating,
)

_STAGE_LABELS = {
    "research": "研究经理",
    "trader": "交易员",
    "portfolio": "组合经理",
}


def _esc(text: str) -> str:
    if not text:
        return ""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def collect_integrity_findings(final_state: Mapping) -> list[dict]:
    """Return the run's integrity findings, recomputing for legacy states.

    When ``integrity_findings`` is present (any run after the reconciliation
    node was added) it is authoritative and is returned as-is — recomputing
    would double-count the PM self-check the node already ran.
    """
    if "integrity_findings" in final_state:
        return [f for f in (final_state.get("integrity_findings") or []) if isinstance(f, dict)]

    decision = final_state.get("final_trade_decision") or ""
    if not decision:
        return []
    # Legacy path only, and it stays: states old enough to lack
    # ``integrity_findings`` are exactly the states whose markdown still carries
    # ``**Target Position**``, so this rating/target check is still meaningful for
    # them. Current runs render a ``**Risk Ceiling**`` instead and get their
    # equivalent check inside the portfolio allocator.
    current_pct, target_pct = parse_position_percents(decision)
    legacy = check_rating_action_consistency(parse_rating(decision), current_pct, target_pct)
    return [legacy] if legacy else []


def split_data_completeness_findings(
    findings: list[dict] | None,
) -> tuple[list[dict], list[dict]]:
    """Split into (data-completeness findings, everything else).

    A renderer that already shows the richer per-field completeness table wants
    only the second list, or the same gap is reported twice in one report.
    """
    items = [f for f in (findings or []) if isinstance(f, dict)]
    completeness = [
        f for f in items
        if str(f.get("section", "")).startswith(DATA_COMPLETENESS_SECTION_PREFIX)
    ]
    other = [
        f for f in items
        if not str(f.get("section", "")).startswith(DATA_COMPLETENESS_SECTION_PREFIX)
    ]
    return completeness, other


def build_integrity_banner(findings: list[dict] | None) -> str:
    """Render the integrity banner, or an empty string when the run was clean.

    ``severity="block"`` findings are rendered prominently but never abort the
    report — see the contract in :mod:`tradingagents.agents.utils.integrity`.
    """
    high, warns = classify_integrity_findings(findings)
    if not high and not warns:
        return ""

    rows = "".join(
        f'<tr><td>{"🚫 严重" if f.get("severity") == SEVERITY_BLOCK else "⚠️ 提示"}</td>'
        f'<td>{_esc(str(f.get("section", "")))}</td>'
        f'<td>{_esc(str(f.get("reason", "")))}</td>'
        f'<td style="font-family:monospace;font-size:12px;color:#666;">'
        f'{_esc(str(f.get("snippet", "")))}</td></tr>'
        for f in list(high) + list(warns)
    )

    summary_parts = []
    if high:
        summary_parts.append(f"{len(high)} 项严重问题")
    if warns:
        summary_parts.append(f"{len(warns)} 项提示")
    summary = "、".join(summary_parts)

    return f"""
<div class="section" style="background: #fdf3f5; border: 2px solid #c2185b; border-left-width: 6px;">
<h2 style="color: #880e4f; border-bottom-color: #c2185b;">🔍 流程完整性提示</h2>
<p style="margin-bottom: 12px; color: #880e4f; font-weight: 600;">
本次运行检测到 {summary}（输出缺失 / 能力降级 / 跨阶段分歧 / 数据不完整）。
分析结论已完整保留、未被改写，但请先阅读下表再采信结论。
</p>
<table class="data-table" style="font-size: 13px;">
<tr><th style="width:80px;">级别</th><th style="width:150px;">环节</th>
<th>说明</th><th style="width:240px;">诊断信息</th></tr>
{rows}
</table>
</div>
"""


def build_stage_rating_table(final_state: Mapping) -> str:
    """Side-by-side table of the three stages' ratings.

    Makes an override visible at a glance: the 2026-08-11 run's
    Hold → Hold → Underweight sequence was only discoverable by reading three
    separate report sections in full.
    """
    ratings = stage_ratings(final_state)
    if not any(ratings.values()):
        return ""
    cells = "".join(
        f"<tr><td>{_STAGE_LABELS[key]}</td>"
        f'<td><strong>{_esc(ratings[key]) or "—（未产出可读评级）"}</strong></td></tr>'
        for key in ("research", "trader", "portfolio")
    )
    return f"""
<h4>各阶段结论对照</h4>
<p style="font-size:13px;color:#666;">
三者都是<strong>观点评级</strong>（证据偏向）——仓位的增减标签不在这张表里，它由组合分配层
在本批全部标的完成后给出。中性观点搭配一次减仓属正常（额度由波动率决定），此表方向相反才是分歧。
</p>
<table class="metadata-table" style="max-width:420px;">
<tr><th style="text-align:left;padding:8px 12px;">阶段</th>
<th style="text-align:left;padding:8px 12px;">评级</th></tr>
{cells}
</table>
"""


def stage_rating_note(final_state: Mapping, stage: str) -> str:
    """Inline badge for a stage heading, e.g. ``（评级：Underweight）``."""
    rating = stage_ratings(final_state).get(stage, "")
    if not rating:
        return ""
    return f'<span style="font-weight:400;color:#667eea;">（评级：{_esc(rating)}）</span>'
